# Generated by Django 5.2 on 2025-04-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_quartier', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
